//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetupTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Company { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime InviteDate { get; set; }
        public Nullable<bool> Rsvp { get; set; }
        public Nullable<bool> Attended { get; set; }
        public string InvitationCode { get; set; }
    
        public virtual MeetupEvent MeetupEvent { get; set; }
    }
}
